[project]
name = "dataproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.1"
dependencies = [
    "blinker>=1.9.0",
    "cachelib>=0.13.0",
    "certifi>=2026.1.4",
    "cftime>=1.6.5",
    "charset-normalizer>=3.4.4",
    "click>=8.3.1",
    "dash>=3.4.0",
    "dash-ag-grid>=33.3.3",
    "dash-bootstrap-components>=2.0.4",
    "flask>=3.1.2",
    "flask-caching>=2.3.1",
    "idna>=3.11",
    "importlib-metadata>=8.7.1",
    "itsdangerous>=2.2.0",
    "jinja2>=3.1.6",
    "markupsafe>=3.0.3",
    "narwhals>=2.15.0",
    "nest-asyncio>=1.6.0",
    "netcdf4>=1.7.4",
    "numpy>=2.4.2",
    "packaging>=26.0",
    "pandas>=3.0.0",
    "plotly>=6.5.2",
    "pyarrow>=23.0.0",
    "python-dateutil>=2.9.0.post0",
    "pytz>=2025.2",
    "requests>=2.32.5",
    "retrying>=1.4.2",
    "setuptools>=80.10.2",
    "six>=1.17.0",
    "tqdm>=4.67.2",
    "typing-extensions>=4.15.0",
    "tzdata>=2025.3",
    "urllib3>=2.6.3",
    "werkzeug>=3.1.5",
    "zipp>=3.23.0",
]
